### ISSUE TITLE
Matrix Voice has 7 microphones not 8

### ISSUE THREAD

**Issue by marcin-sielski** [matrix-io/matrix-documentation#106]
Small correction is required at https://matrix-io.github.io/matrix-documentation/ under "MATRIX Voice" section.

**Comment by Hermitter** [comment]
Hey @marcin-sielski, The MATRIX Voice does have 8 microphones. 7 Around and 1 in the center.

**Comment by marcin-sielski** [comment]
I just noticed. Thank you.
