### ISSUE TITLE
I can not reach you by mail or contact form ... seeking attention via different channels....

### ISSUE THREAD

**Issue by Dimitar-Boychev** [matrix-io/matrix-documentation#109]
No one is reading shipping@matrixlabs.ai maybe you need to add this to the documentation.
The contact form on https://www.matrix.one/contact  didn't have any effect also... 
I hope you are all well, but I am forced to look for your attention via different channels...
I have a one month old order and I have no update if it is going to happen or I can have my money back....

**Comment by AlieGG** [comment]
Hello @Dimitar-Boychev thanks for reaching out on GitHub. We just emailed you to resolve this issue.
