### ISSUE TITLE
Widget Config Trigger: missing

### ISSUE THREAD

**Issue by Hermitter** [matrix-io/matrix-documentation#25]
I could not find trigger: mentioned in the documentation.

**Comment by brianofrokk3r** [comment]
@eighteyes

**Comment by brianofrokk3r** [comment]
@Hermitter please be more explanative of this issue or we will close it.

**Comment by Hermitter** [comment]
It's the trigger: option for widgets
range:
    control: range
    **trigger**: numberOfLeds
    value: 'Number of leds'
    label: 'Number of leds'
    min: 0
    max: 35

**Comment by Hermitter** [comment]
Widget Config Trigger is now documented here:
https://matrix-io.github.io/matrix-documentation/matrix-os/reference/widgets/#widget-configuration
