### ISSUE TITLE
REST API for reporting data

### ISSUE THREAD

**Issue by WorldWideWebb** [matrix-io/matrix-documentation#77]
I haven't been able to find any documentation on your REST API for pulling reporting data (reporting data from dash.matrix.one). I've heard it's "in the works," but it's been quite some time.

**Comment by WorldWideWebb** [comment]
When I log into the dashboard, there is an export feature at the top that exports CSV data for an application. Is there a way to programmatically get that data out without having to log into the dashboard and export it by hand?

**Comment by Hermitter** [comment]
Sorry, we do not support that feature for the dashboard. Currently, we don't have any plans for implementing this.
